Repository kubernetes/federation, pull requests merged in 2018-03, with the labels that each got.

#239 Fix broken DNS CNAME chain for cross-cluster service discovery
  pkg/federation-controller/service/ingress/ingress.go
  pkg/federation-controller/service/servicecontroller.go
  pkg/federation-controller/service/servicecontroller_test.go
  pkg/kubefed/init/init.go
  pkg/kubefed/init/init_test.go
  pkg/kubefed/join.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/multicluster, size/S

#246 Fix comparison of golang versions
  hack/lib/golang.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#245 Fix deepcopy invocation of federated ingress spec to cluster ingress …
  pkg/federation-controller/ingress/BUILD
  pkg/federation-controller/ingress/ingress_controller.go
  pkg/federation-controller/ingress/ingress_controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/multicluster, size/S

#244 Update kubefed.go
  pkg/kubefed/kubefed.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#223 Clarified how to run container from make quick-release
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#219 Federation Provider for Azuredns
  Gopkg.lock
  Gopkg.toml
  cmd/federation-controller-manager/app/BUILD
  cmd/federation-controller-manager/app/plugins.go
  pkg/dnsprovider/BUILD
  pkg/dnsprovider/providers/azure/azuredns/BUILD
  pkg/dnsprovider/providers/azure/azuredns/azuredns.go
  pkg/dnsprovider/providers/azure/azuredns/azuredns_test.go
  pkg/dnsprovider/providers/azure/azuredns/helpers.go
  pkg/dnsprovider/providers/azure/azuredns/interface.go
  pkg/dnsprovider/providers/azure/azuredns/rrchangeset.go
  pkg/dnsprovider/providers/azure/azuredns/rrset.go
  pkg/dnsprovider/providers/azure/azuredns/rrsets.go
  pkg/dnsprovider/providers/azure/azuredns/stubs/BUILD
  pkg/dnsprovider/providers/azure/azuredns/stubs/azurednsapi.go
  pkg/dnsprovider/providers/azure/azuredns/zone.go
  pkg/dnsprovider/providers/azure/azuredns/zones.go
  vendor/BUILD
  vendor/github.com/Azure/azure-sdk-for-go/arm/dns/BUILD
  vendor/github.com/Azure/azure-sdk-for-go/arm/dns/client.go
  vendor/github.com/Azure/azure-sdk-for-go/arm/dns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/arm/dns/recordsets.go
  vendor/github.com/Azure/azure-sdk-for-go/arm/dns/version.go
  vendor/github.com/Azure/azure-sdk-for-go/arm/dns/zones.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#248 Fix for deployment/replicaset delete problems
  pkg/federatedtypes/deployment.go
  pkg/federatedtypes/replicaset.go
  pkg/federatedtypes/scheduling.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#249 fix broken link
  docs/api-reference/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#247 Alternative path (then default usage of RBAC) for kubefed cluster access
  pkg/kubefed/init/init.go
  pkg/kubefed/init/init_test.go
  pkg/kubefed/join.go
  pkg/kubefed/join_test.go
  pkg/kubefed/unjoin.go
  pkg/kubefed/unjoin_test.go
  pkg/kubefed/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L
